---
- hosts: localhost
  connection: local
  tasks:
  - name: Enable remote access
    lineinfile: dest=/etc/mysql/my.cnf regexp='bind-address' line='bind-address=0.0.0.0'
    when: ansible_os_family == "Debian"
    
  - name: Enable remote access
    lineinfile: dest=/etc/my.cnf regexp='bind-address' line='bind-address=0.0.0.0'
    when: ansible_os_family == "RedHat"
    
  - name: Start MySQL service
    service: name=mariadb state=restarted enabled=yes
    when: ansible_os_family == "RedHat"
    
  - name: Start MySQL service
    service: name=mysql state=restarted enabled=yes
    when: ansible_os_family == "Debian"

  - name: update mysql root password for all root accounts
    mysql_user: name=root password={{root_password}}
    ignore_errors: yes
