---
- hosts: localhost
  connection: local
  vars:
    docker_bridge_ip_cidr: "172.0.17.1/24"
  tasks:

    - name: Call Docker role
      include_role:
        name: indigo-dc.docker

    - name: "Install docker-compose"
      pip: name="docker-compose" state="present"

    - name: "create directory path to store the configuration files"
      file:
        path: "/opt/{{ project_name }}"
        state: directory
        mode: 0755

    - name: debug
      debug: 
        var: environment_variables

    - name: Set environment variables
      lineinfile:
        path: /opt/{{ project_name }}/.env
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      with_dict: "{{ environment_variables }}"

    - name: Add HOST_PUBLIC_IP environment variable
      lineinfile:
        path: /opt/{{ project_name }}/.env
        line: "HOST_PUBLIC_IP={{IM_NODE_PUBLIC_IP}}"
        create: yes

    - name:
      get_url:
        url: "{{ docker_compose_file_url }}"
        dest: "/opt/{{ project_name }}/docker-compose.yaml"

    - name: "Start the service"
      docker_service:
        project_src: "/opt/{{ project_name }}"
        state: present
