---
- hosts: localhost
  connection: local
  tasks:
  - name: Check for apache presence and install PHP support
    apt: name=apache2,php5,php5-mysql update_cache=yes state=present
  - name: Retrieve Web Application from download url
    get_url: url={{download_url}} dest=/tmp
  - name: Unpacking Web Application
    unarchive: src="/tmp/cellar-webapp-sql.tgz" dest="/var/www/html" copy=no
  - name: Modify required configuration files
    replace:
      dest: /var/www/html/cellar-webapp-sql/api/index.php
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    with_items:
      - regexp: '.*\$dbuser=.*'
        replace: ' $dbuser="{{db_user}}";'
      - regexp: '.*\$dbpass=.*'
        replace: ' $dbpass="{{db_password}}";'
      - regexp: '.*\$dbname=.*'
        replace: ' $dbname="{{db_name}}";'
      - regexp: '.*\$dbhost=.*'
        replace: ' $dbhost="{{db_host}}";'
      - regexp: '.*\?>.*'
        replace: '*/?>'
  - name: Modify apache configuration to allow rewrite
    replace:
      dest: /etc/apache2/apache2.conf
      regexp: "None"
      replace: "All"
  - name: Enable rewrite module in apache
    command: /usr/sbin/a2enmod rewrite
  - name: Restart apache
    service: name=apache2 state=restarted
